# @package metric_params
defaults:
  - filters: default_detection3d_filters
  - collision_models: default_collision_model
  - components: default_detection3d_components
  - _self_

collision:
  _target_: autoware_ml.metrics.detection3d.collision.CollisionTTC
  class_names: ${database.database_task_configs.detection3d.label_names}
  map_provider: ${datamodule.test_dataset.map_provider}
  vehicle: ${metric_params.collision_models.vehicle}
  region: ${metric_params.collision_models.drivable_region}
  max_speed_mps: ${metric_params.collision_models.max_speed_mps}
  params: ${metric_params.collision_models.reachability}

# Grouped classes for evaluation
class_groups:
  grouped_vehicle: [car, truck, bus, train, vehicle_extension]
  grouped_two_wheeler: [motorcycle, bicycle]
  grouped_pedestrian_animal: [pedestrian, animal]
  grouped_static_obstacle: [barrier, traffic_cone]
  grouped_debris: [debris]
  grouped_structure: [bicycle_rack]
