defaults:
  - default_datamodule@_here_
  - nuscenes/datasets@_global_.datasets.train: default_segmentation3d_train_dataset
  - nuscenes/datasets@_global_.datasets.test: default_segmentation3d_test_dataset
