defaults:
  - default_datamodule@_here_
  - nuscenes/datasets@_global_.datasets.train: default_calibration_status_train_dataset
  - nuscenes/datasets@_global_.datasets.test: default_calibration_status_test_dataset
