defaults:
  - default_datamodule@_here_
  - t4dataset/datasets/segmentation3d@_global_.datasets.train: default_segmentation3d_train_dataset
  - t4dataset/datasets/segmentation3d@_global_.datasets.test: default_segmentation3d_test_dataset
