_target_: autoware_ml.databases.database_task_configs.DatabaseTaskConfig
_convert_: all

defaults:
  - labels@label_names: default_label_names
  - labels@label_remapper: default_label_remapper
  - _self_

# Must match TaskType.DETECTION3D.value
task_type:
  _target_: autoware_ml.types.tasks.TaskType
  _convert_: all
  _args_: [detection3d]

ignore_label_index: -1
